version: '3.8'

services:
  backend:
    container_name: checkout-backend
    build:
      context: backend
    ports:
      - "8000:8000"
  
  frontend:
    container_name: checkout-frontend
    build:
      context: frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: "http://checkout-backend:8000"
